controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
api_product_index:
    path: /api/products
    controller: 'App\Controller\ProductController::index'
    methods: ['GET']
